name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run tests
      run: go test -race ./...
